# Config file for automatic testing at travis-ci.org
dist: xenial   # required for Python >= 3.7

language: python

services:
  - docker

before_install:
  - docker-compose -v
  - docker -v

install: pip install -r requirements.txt

matrix:
  include:	
    - name: Test
      python: 3.7
      script: ./scripts/clean && ./scripts/test
    - name: Lint	
      script: ./scripts/lint
